#! /usr/bin/perl

# /usr/lib/urxvt/perl/clipboard yaourt -S xsel
sub on_sel_grab {
    my $query=quotemeta $_[0]->selection;
    $query=~ s/\n/\\n/g;
    $query=~ s/\r/\\r/g;
    system( "echo -en " . $query . " | xsel -i -b -p" );
}

